// app/pages/files/[code].vue
<template>
  <div v-if="pending" class="flex items-center justify-center h-full min-h-[60vh]">
    <span class="loading loading-infinity loading-xl" />
  </div>
  
  <div v-else-if="error || !fileInfo" class="flex justify-center items-center flex-col gap-2 w-auto h-full min-h-[60vh]">
    <p>File not found</p>
    <NuxtLink to="/" class="btn btn-primary">Go Home</NuxtLink>
  </div>
  
  <template v-else>
    <!-- Image Viewer -->
    <ImageViewer
      v-if="isImage"
      :src="rawURL"
      :alt="code"
      :width="fileInfo.width"
      :height="fileInfo.height"
    />
    
    <!-- Video Player -->
    <VideoPlayer v-else-if="isVideo" :video-u-r-l="rawURL" />
    
    <!-- Audio Player with Visualizer -->
    <AudioVisualizer v-else-if="isAudio" :audio-u-r-l="rawURL" />
    
    <!-- Markdown Viewer -->
    <MarkdownViewer v-else-if="isMarkdown" :code="code" />
    
    <!-- Text Viewer -->
    <TextViewer v-else-if="isText" :code="code" />
    
    <!-- PDF Viewer -->
    <div v-else-if="isPdf" class="w-full h-full object-contain min-h-[80vh]">
      <iframe
        :src="rawURL"
        class="w-full h-full min-h-[80vh]"
        title="File Content"
      />
    </div>
    
    <!-- Default Download View -->
    <div v-else class="flex justify-center items-center flex-col gap-2 w-auto h-full min-h-[60vh] px-4">
      <p class="text-center break-all">{{ fileInfo.rawName }}</p>
      <div class="flex gap-2 sm:gap-4 flex-wrap justify-center">
        <a class="btn btn-primary btn-sm sm:btn-md" :href="downloadURL" download>
          Download
        </a>
        <a class="btn btn-primary btn-sm sm:btn-md" :href="infoURL">
          Info
        </a>
        <a class="btn btn-primary btn-sm sm:btn-md" :href="rawURL" target="_blank" rel="noopener noreferrer">
          Raw
        </a>
      </div>
    </div>
  </template>
</template>

<script setup lang="ts">
interface FileInfo {
  code: string
  url: string
  rawName: string
  type: string
  size: string
  rawSize: number
  date: string
  unixDate: number
  ago: string | null
  downloadCount: number
  checksum: string
  width?: number
  height?: number
  thumbnail?: string
}

const route = useRoute()
const config = useRuntimeConfig()

const code = computed(() => route.params.code as string)

const { data: fileInfo, pending, error } = await useFetch<FileInfo>(`/api/v1/info/${code.value}`)

const baseURL = config.public.url
const downloadURL = computed(() => `/api/v1/download/${code.value}`)
const rawURL = computed(() => `/api/v1/raw/${code.value}`)
const infoURL = computed(() => `/api/v1/info/${code.value}`)

const extension = computed(() => {
  if (!code.value) return ''
  const parts = code.value.split('.')
  if (parts.length <= 1) return ''
  const ext = parts[parts.length - 1]
  return ext?.toLowerCase() ?? ''
})

const isImage = computed(() => ['jpg', 'jpeg', 'webp', 'svg', 'png', 'gif'].includes(extension.value))
const isVideo = computed(() => ['mp4', 'mov', 'avi', 'webm'].includes(extension.value))
const isAudio = computed(() => ['wav', 'mp3', 'ogg'].includes(extension.value))
const isMarkdown = computed(() => ['md', 'markdown'].includes(extension.value))
const isText = computed(() => ['txt', 'log', 'json', 'xml', 'yaml', 'yml', 'toml', 'ini', 'cfg', 'conf', 'sh', 'bash', 'zsh', 'fish', 'ps1', 'bat', 'cmd', 'js', 'ts', 'jsx', 'tsx', 'vue', 'svelte', 'html', 'htm', 'css', 'scss', 'sass', 'less', 'py', 'rb', 'php', 'java', 'kt', 'swift', 'go', 'rs', 'c', 'cpp', 'h', 'hpp', 'cs', 'fs', 'lua', 'r', 'sql', 'graphql', 'dockerfile', 'makefile', 'cmake', 'gradle', 'env', 'gitignore', 'gitattributes', 'editorconfig'].includes(extension.value))
const isPdf = computed(() => extension.value === 'pdf')

// Meta tags for social media
useHead(() => {
  const file = fileInfo.value
  if (!file) return {}
  
  const meta: any[] = [
    { property: 'og:site_name', content: config.public.name },
    { property: 'og:title', content: code.value },
    { property: 'og:description', content: `Original Filename: ${file.rawName}` },
    { property: 'og:image', content: file.thumbnail || rawURL.value },
  ]
  
  if (isVideo.value) {
    meta.push(
      { name: 'twitter:card', content: 'player' },
      { name: 'twitter:title', content: code.value },
      { name: 'twitter:description', content: `Original Filename: ${file.rawName}` },
      { name: 'twitter:image', content: file.thumbnail || rawURL.value },
    )
  } else if (isImage.value) {
    meta.push(
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: code.value },
      { name: 'twitter:description', content: `Original Filename: ${file.rawName}` },
      { name: 'twitter:image', content: rawURL.value },
    )
  }
  
  return {
    title: code.value,
    meta,
  }
})
</script>

// src/app/files/[code]/page.tsx
import fs from "node:fs"
import path from "node:path"
import type { Metadata } from "next"
import { headers } from "next/headers"
import { notFound } from "next/navigation"
import { imageSize } from "image-size"
import ImageViewer from "@/components/ImageViewer"
import Waveform from "@/components/Waveform"
import Markdown from "@/components/MarkdownViewer"

const DOWNLOAD_URL = `${process.env.URL}/api/v1/download/`
const RAW_URL = `${process.env.URL}/api/v1/raw/`
const THUMBNAIL_URL = `${process.env.URL}/api/v1/thumbnail/`
const USER_AGENTS = [
  "SummalyBot",
  "Pleroma",
  "Akkoma",
  "Mastodon",
  "Discordbot",
]

type Props = {
  params: Promise<{
    code: string
  }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const headersList = headers()
  const userAgent = (await headersList).get("user-agent") || "Unknown"

  if (USER_AGENTS.some((ua) => userAgent.includes(ua))) {
    const detectedUserAgent = USER_AGENTS.find((ua) => userAgent.includes(ua))
    console.log(`User-Agent detected: ${detectedUserAgent}`)
  }

  const filesDir = process.env.FILES_DIR || path.join(process.cwd(), "files")
  const fileDir = path.join(filesDir, (await params).code)
  const file = fs.readdirSync(fileDir)

  if (!fs.existsSync(fileDir)) {
    return {
      title: "Not Found",
      description: "The requested file is not found.",
      openGraph: {
        siteName: process.env.NEXT_PUBLIC_NAME,
        title: "Not Found",
        description: "The requested file is not found.",
      },
    }
  }

  const fileName = file[0]

  let metadata: Metadata = {
    title: (await params).code,
    description: `Original Filename: ${fileName}`,
    openGraph: {
      siteName: process.env.NEXT_PUBLIC_NAME,
      title: (await params).code,
      description: `Original Filename: ${fileName}`,
      images: `${RAW_URL}${(await params).code}`,
    },
  }

  if ((await params).code.match(/.mp4|.mov|.avi|.webm/)) {
    metadata = {
      ...metadata,
      twitter: {
        card: "player",
        siteId: (await params).code,
        title: (await params).code,
        description: `Original Filename: ${fileName}`,
        site: process.env.NEXT_PUBLIC_NAME,
        creator: process.env.AUTHOR,
        creatorId: process.env.AUTHOR_ID,
        images: `${THUMBNAIL_URL}${(await params).code}`,
        players: [
          {
            playerUrl: `${RAW_URL}${(await params).code}`,
            streamUrl: "",
            width: 320,
            height: 180,
          },
        ],
      },
    }
    metadata.openGraph = {
      ...metadata.openGraph,
      images: `${THUMBNAIL_URL}${(await params).code}`,
    }
  } else if ((await params).code.match(/.jpg|.jpeg|.png|.gif/)) {
    metadata = {
      ...metadata,
      twitter: {
        card: "summary_large_image",
        siteId: (await params).code,
        title: (await params).code,
        site: process.env.NEXT_PUBLIC_NAME,
        creator: process.env.AUTHOR,
        creatorId: process.env.AUTHOR_ID,
        description: `Original Filename: ${fileName}`,
        images: `${RAW_URL}${(await params).code}`,
      },
    }
  }

  return metadata
}

export default async function Page({ params }: Props) {
  const filesDir = process.env.FILES_DIR || path.join(process.cwd(), "files")

  if (!fs.existsSync(path.join(filesDir, (await params).code))) {
    return notFound()
  }

  const fileDir = path.join(filesDir, (await params).code)
  const file = fs.readdirSync(fileDir)
  const fileName = file[0]

  const downloadURL = `${DOWNLOAD_URL}${(await params).code}`
  const rawURL = `${RAW_URL}${(await params).code}`
  const infoURL = `${process.env.URL}/api/v1/info/${(await params).code}`
  const fileExtension = path.extname((await params).code)
  const cleanedFileExtension = fileExtension.replace(".", "")

  switch (cleanedFileExtension) {
    case "jpg":
    case "jpeg":
    case "webp":
    case "svg":
    case "png":
    case "gif": {
      const fileDir = path.join(filesDir, (await params).code)
      const file = fs.readdirSync(fileDir)
      const fileName = file[0]

      const imageSizeData = imageSize(path.join(fileDir, fileName))

      return (
        <>
          <ImageViewer
            src={rawURL}
            alt={(await params).code}
            width={imageSizeData.width}
            height={imageSizeData.height}
          />
        </>
      )
    }
    case "mp4":
    case "mov":
    case "avi":
    case "webm":
      return (
        <>
          <video className="w-full h-full object-contain" controls>
            <source src={rawURL} type={`video/${cleanedFileExtension}`} />
            <track
              src={`${rawURL}.vtt`}
              kind="captions"
              srcLang="en"
              label="English"
              default
            />
          </video>
        </>
      )
    case "wav":
    case "mp3":
    case "ogg":
      return (
        <>
          <Waveform audioURL={rawURL} />
        </>
      )
    case "txt":
    case "pdf":
      return (
        <>
          <div className="w-full h-full object-contain">
            <iframe
              src={rawURL}
              className="w-full h-full"
              title="File Content"
            />
          </div>
        </>
      )
    case "md":
      return <Markdown id={(await params).code} />
    default:
      return (
        <>
          <div className="flex justify-center items-center flex-col gap-2 w-auto h-full">
            <p>{fileName}</p>
            <div className="flex gap-4">
              <a className="btn btn-primary " href={downloadURL} download>
                Download
              </a>
              <a className="btn btn-primary" href={infoURL}>
                Info
              </a>
            </div>
          </div>
        </>
      )
  }
}
